# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class PostBookRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, isbn=None, title=None, author=None):  # noqa: E501
        """PostBookRequest - a model defined in OpenAPI

        :param isbn: The isbn of this PostBookRequest.  # noqa: E501
        :type isbn: str
        :param title: The title of this PostBookRequest.  # noqa: E501
        :type title: str
        :param author: The author of this PostBookRequest.  # noqa: E501
        :type author: str
        """
        self.openapi_types = {
            'isbn': str,
            'title': str,
            'author': str
        }

        self.attribute_map = {
            'isbn': 'isbn',
            'title': 'title',
            'author': 'author'
        }

        self._isbn = isbn
        self._title = title
        self._author = author

    @classmethod
    def from_dict(cls, dikt) -> 'PostBookRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The postBook_request of this PostBookRequest.  # noqa: E501
        :rtype: PostBookRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def isbn(self):
        """Gets the isbn of this PostBookRequest.


        :return: The isbn of this PostBookRequest.
        :rtype: str
        """
        return self._isbn

    @isbn.setter
    def isbn(self, isbn):
        """Sets the isbn of this PostBookRequest.


        :param isbn: The isbn of this PostBookRequest.
        :type isbn: str
        """

        self._isbn = isbn

    @property
    def title(self):
        """Gets the title of this PostBookRequest.


        :return: The title of this PostBookRequest.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this PostBookRequest.


        :param title: The title of this PostBookRequest.
        :type title: str
        """

        self._title = title

    @property
    def author(self):
        """Gets the author of this PostBookRequest.


        :return: The author of this PostBookRequest.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author):
        """Sets the author of this PostBookRequest.


        :param author: The author of this PostBookRequest.
        :type author: str
        """

        self._author = author
