# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Shelf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, shelf_id=None, books=None, created_at=None, updated_at=None):  # noqa: E501
        """Shelf - a model defined in OpenAPI

        :param shelf_id: The shelf_id of this Shelf.  # noqa: E501
        :type shelf_id: str
        :param books: The books of this Shelf.  # noqa: E501
        :type books: List[str]
        :param created_at: The created_at of this Shelf.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this Shelf.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'shelf_id': str,
            'books': List[str],
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'shelf_id': 'shelfId',
            'books': 'books',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }

        self._shelf_id = shelf_id
        self._books = books
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'Shelf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Shelf of this Shelf.  # noqa: E501
        :rtype: Shelf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def shelf_id(self):
        """Gets the shelf_id of this Shelf.


        :return: The shelf_id of this Shelf.
        :rtype: str
        """
        return self._shelf_id

    @shelf_id.setter
    def shelf_id(self, shelf_id):
        """Sets the shelf_id of this Shelf.


        :param shelf_id: The shelf_id of this Shelf.
        :type shelf_id: str
        """

        self._shelf_id = shelf_id

    @property
    def books(self):
        """Gets the books of this Shelf.


        :return: The books of this Shelf.
        :rtype: List[str]
        """
        return self._books

    @books.setter
    def books(self, books):
        """Sets the books of this Shelf.


        :param books: The books of this Shelf.
        :type books: List[str]
        """

        self._books = books

    @property
    def created_at(self):
        """Gets the created_at of this Shelf.


        :return: The created_at of this Shelf.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Shelf.


        :param created_at: The created_at of this Shelf.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this Shelf.


        :return: The updated_at of this Shelf.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this Shelf.


        :param updated_at: The updated_at of this Shelf.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
